# This is the main build command and publish directory for your Expo web app.
[build]
  publish = "dist" # Or "web-build", verify your Expo output folder name
  command = "npx expo export --platform web"

[build.environment]
  NODE_VERSION = "18"

# --- REDIRECTS ---
# All redirects are now consolidated here. The _redirects file should be deleted.
# Netlify processes redirects from top to bottom. Specific rules must come before general rules.

# Rule 1: Strip tracking parameters from URLs
# These perform 301 Permanent Redirects, which clean the URL in the browser bar
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 301
  force = true
  query = {fbclid = ":fbclid"}

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 301
  force = true
  query = {gclid = ":gclid"}

# Rule 2: Single Page App (SPA) Fallback.
# This is the last rule. It serves your app's main index.html for any path
# that did not match a previous redirect rule or a static file in the publish directory.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # No "force = true" here, so it doesn't override existing files like ads.txt

# --- HEADERS ---
# These are good for security and SEO.

# General security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Long-term caching for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Correct content types for important files
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"