[build]
  publish = "dist"
  command = "npx expo export --platform web"

# Strip Facebook tracking parameters FIRST (before other redirects)
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true
  conditions = {Query = "fbclid"}

# Specific redirect for Facebook link /lander
[[redirects]]
  from = "/lander"
  to = "/"
  status = 301
  force = true

# Handle bot crawlers differently - serve static content
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {User-Agent = "!*bot*,!*crawler*,!*spider*,!*Googlebot*,!*AdsBot*"}

# For bots, serve the main page directly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {User-Agent = "*bot*,*crawler*,*spider*,*Googlebot*,*AdsBot*"}

[build.environment]
  NODE_VERSION = "18"

# Headers for better SEO and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Allow crawlers
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
